name: Sync Fork

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch: 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: gmst-sa
          repo: 2024-api
          base: main
          head: main
